//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotreBourse_ProduitsChimiques.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Annonce
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "this Field Is Required")]
        public Nullable<System.DateTime> DatePublicationAnnonce { get; set; }
        [Required(ErrorMessage = "this Field Is Required")]
        public Nullable<int> Validite { get; set; }
        [Required(ErrorMessage = "this Field Is Required")]
        public string EtatAnnonce { get; set; }
        [Required(ErrorMessage = "this Field Is Required")]
        public string TypeAnnonce { get; set; }
        [Required(ErrorMessage = "this Field Is Required")]
        public int IdAuteur { get; set; }
        [Required(ErrorMessage = "this Field Is Required")]
        public int IdProduit { get; set; }
        [Required(ErrorMessage = "this Field Is Required")]
        public Nullable<int> Quantite { get; set; }
        [DataType(DataType.DateTime), Required(ErrorMessage = "this Field Is Required")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DateExpirationProduit { get; set; }
        [Required(ErrorMessage = "this Field Is Required")]
        public string TypeTransaction { get; set; }
        [Required(ErrorMessage = "this Field Is Required"),DataType(DataType.MultilineText)]
        public string Commentaires { get; set; }


    }
}
