//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotreBourse_ProduitsChimiques.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Magasin
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "this Field Is Required")]
        public string Code { get; set; }
        [Required(ErrorMessage = "this Field Is Required")]
        public string Nom { get; set; }
        [Required(ErrorMessage = "this Field Is Required")]
        public string Structure { get; set; }
        [Required(ErrorMessage = "this Field Is Required")]
        public string TypeStructure { get; set; }
        public Nullable<int> Responsable { get; set; }
    }
}
