//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotreBourse_ProduitsChimiques.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Message()
        {
            this.Message1 = new HashSet<Message>();
        }
    
        public int Id { get; set; }
        public int IdEmetteur { get; set; }
        public int IdDestinataire { get; set; }
        public Nullable<System.DateTime> DateMessage { get; set; }
        public int IdReplyTo { get; set; }
        public string Objet { get; set; }
        public string Contenu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Message1 { get; set; }
        public virtual Message Message2 { get; set; }
    }
}
