//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotreBourse_ProduitsChimiques.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Produit
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "this Field Is Required")]
        public string Label { get; set; }
        [Required(ErrorMessage = "this Field Is Required")]
        public string CAS { get; set; }
        [Required(ErrorMessage = "this Field Is Required")]
        public string Unite { get; set; }
        [Required(ErrorMessage = "this Field Is Required")]
        public string Etat { get; set; }
    }
}
