//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotreBourse_ProduitsChimiques.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int IdUser { get; set; }
        [DisplayName("Nom d'utilisateur")]
        [Required(ErrorMessage = "this Field Is Required")]
        public string Username { get; set; }
        [DisplayName("Mot de passe")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "this Field Is Required")]
        public string Password { get; set; }
        public string Type { get; set; }
        public string Nom { get; set; }
        public string Email { get; set; }
        public string LoginErrorMessage { get; set; }

    }
}
